### ISSUE TITLE
library not working with Due (ILI9327 8-bit 3.5" TFT mcufriend)

### ISSUE THREAD

**Issue by Nulista** [dgolda/UTFT#3]
Hello,

the library working great with de Mega but not with the due.
This is the fault message:

In file included from C:\test\libraries\UTFT-master\UTFT.cpp:83:0:
C:\test\libraries\UTFT-master\hardware/arm/HW_SAM3X8E.h:9:51: error: no 'void UTFT::LCD_Writ_Bus(char, char, byte)' member function declared in class 'UTFT'
 void UTFT::LCD_Writ_Bus(char VH,char VL, byte mode)
                                                   ^
Fout bij het compileren.

Wat is the problem? can you help me?

thanks
